name: Release to Docker Hub

on:
  release:
    types: [published]

env:
  # Only used locally for validating image
  TEST_TAG: "${{ env.DOCKER_IMAGE_NAME }}:test"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Determine the tags to publish based on the release tag
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            # publish by version on all release tags, and `latest` on stable release tags.
            type=semver,pattern={{version}},latest=${{ !github.event.release.prerelease }}}

            # Originally, I thought that `type=semver,value=rc` would work,
            # but the `value` is actually used to replace the input value,
            # not the output value, which is not clear from the documentation.
            type=match,pattern=v(\d+.\d+.\d+-(rc).\d+),group=2,latest=false

      # Build and test the image
      - name: Build and Test
        uses: docker/build-push-action@v4
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: |
            pyquil_version=${{ github.event.release.tag_name }}
      - name: Test Image
        run: |
          docker run --rm ${{ env.TEST_TAG }} python -c "from pyquil import get_qc; qvm = get_qc('9q-qvm')"

      # Build and publish the image
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            pyquil_version=${{ github.event.release.tag_name }}
